<?php

	$german = array(

	'item:object:event_calendar' => "Event-Kalender",
	'event_calendar:new_event' => "Neues Event",
	'event_calendar:no_such_event_edit_error' => "Fehler: Dieses Event ist nicht verfügbar oder Du hast keine Berechtigung, es zu bearbeiten.",
	'event_calendar:add_event_title' => "Event hinzufügen",
	'event_calendar:manage_event_title' => "Event bearbeiten",
	'event_calendar:manage_event_description' => "Gebe im Folgenden die Einzelheiten zu Deinem Event ein. "
		."Die Angabe von Titel des Events, des Ortes und des Anfangsdatum sind zwingend notwendig. "
		."Du kannst die Kalender-Icons anklicken, um Anfangs- und Enddatum auszuwählen.",
	'event_calendar:title_label' => "Titel",
	'event_calendar:title_description' => "Notwendig. Ein bis vier Worte",
	'event_calendar:brief_description_label' => "Kurzbeschreibung",
	'event_calendar:brief_description_description' => "Optional. Eine kurze Zusammenfassung.",
	'event_calendar:venue_label' => "Ort",
	'event_calendar:venue_description' => "Notwendig. Wo wird dieses Event stattfinden?",
	'event_calendar:start_date_label' => "Anfangsdatum",
	'event_calendar:start_date_description'	=> "Notwendig. Wann wird dieses Event starten?",
	'event_calendar:end_date_label' => "Enddatum",
	'event_calendar:end_date_description'	=> "Optional. Wann ist dieses Event beendet? Das Anfangsdatum wird auch als Enddatum "
		."verwendet, wenn dieses nicht angegeben wird.",
	'event_calendar:start_time_label' => "Anfangszeit",
	'event_calendar:start_time_description'	=> "Optional. Um welche Zeit wird das Event beginnen?",
	'event_calendar:end_time_label' => "Endzeit",
	'event_calendar:end_time_description'	=> "Optional. Um welche Zeit wird das Event enden?",
	'event_calendar:fees_label' => "Eintrittsgeld",
	'event_calendar:fees_description'	=> "Optional. Die Kosten für dieses Event, falls es welche gibt.",
	'event_calendar:contact_label' => "Kontakt",
	'event_calendar:contact_description'	=> "Optional. Die zu kontaktierende Person für mehr Informationen, "
			."vorzugsweise mit einer Telefonnummer oder Emailadresse.",
	'event_calendar:organiser_label' => "Veranstalter",
	'event_calendar:organiser_description'	=> "Optional. Die verantwortliche Person oder der Veranstalter dieses Events.",
	'event_calendar:event_tags_label' => "Tags",
	'event_calendar:event_tags_description'	=> "Optional. Eine durch Kommas getrennte Auflistung von Tags zur Beschreibung des Events.",
	'event_calendar:long_description_label' => "Ausführliche Beschreibung",
	'event_calendar:long_description_description'	=> "Optional. Kann ein Absatz oder wenn notwendig auch länger sein.",
	'event_calendar:manage_event_response' => "Dein Event wurde gespeichert.",
	'event_calendar:add_event_response' => "Dein Event wurde hinzugefügt.",
	'event_calendar:manage_event_error' => "Fehler: Beim Speichern Deines Events ist ein Problem aufgetreten. "
			."Vergewissere Dich, dass Du die notwendigen Felder ausgefüllt hast.",
	'event_calendar:error_nosuchevent' => "Fehler: dieses Event ist nicht verfügbar.",
	'event_calendar:show_events_title' => "Event-Kalender",
	'event_calendar:day_label' => "Tag",
	'event_calendar:week_label' => "Woche",
	'event_calendar:month_label' => "Monat",
	'event_calendar:group' => "Gruppen-Kalender",
	'event_calendar:new' => "Event hinzufügen",
	'event_calendar:submit' => "Speichern",
	'event_calendar:cancel' => "Abbrechen",
	'event_calendar:widget_title' => "Event-Kalender",
	'event_calendar:widget:description' => "Deine Events anzeigen.",
	'event_calendar:num_display' => "Anzahl der anzuzeigenden Events",
	'event_calendar:groupprofile' => "Bevorstehende Events",
	'event_calendar:view_calendar' => "Kalender anzeigen",
	'event_calendar:when_label' => "Wann",
	'event_calendar:site_wide_link' => "Alle Events anzeigen",
	'event_calendar:view_link' => "Dieses Event anzeigen",
	'event_calendar:edit_link' => "Dieses Event bearbeiten",
	'event_calendar:delete_link' => "Dieses Event löschen",
	'event_calendar:delete_confirm_title' => "Löschen des Events bestätigen",
	'event_calendar:delete_confirm_description' => "Bist Du sicher, dass Du dieses Event (\"%s\") löschen willst? Das Löschen kann nicht rückgängig gemacht werden.",
	'event_calendar:delete_response' => "Das Event wurde gelöscht.",
	'event_calendar:error_delete' => "Dieses Event ist nicht verfügbar oder Du hast nicht die Berechtigung, es zu löschen.",
	'event_calendar:delete_cancel_response' => "Löschen des Events abgebrochen.",
	'event_calendar:add_to_my_calendar' => "Zu meinem Kalender hinzufügen",
	'event_calendar:remove_from_my_calendar' => "Aus meinen Kalender entfernen",
	'event_calendar:add_to_my_calendar_response' => "Das Event wurde zu Deinem persönlichen Kalender hinzugefügt.",
	'event_calendar:remove_from_my_calendar_response' => "Das Event wurde aus Deinem persönlichen Kalender entfernt.",
	'event_calendar:users_for_event_title' => "Mitglieder mit Interesse am Event \"%s\"",
	'event_calendar:personal_event_calendars_link' => "Persönliche Event-Kalender (%s)",
	'event_calendar:settings:group_profile_display:title' => "Anzeige des Gruppen-Kalender auf der Profilseite der Gruppe (wenn die Option Gruppen-Kalender aktiviert ist)",
	'event_calendar:settings:group_profile_display_option:left' => "linke Spalte",
	'event_calendar:settings:group_profile_display_option:right' => "rechte Spalte",
	'event_calendar:settings:group_profile_display_option:none' => "nicht anzeigen",
	'event_calendar:settings:times:title' => "Eingabefelder für Anfangs- und Endzeiten der Events zusätzlich zum Datum anzeigen",
	'event_calendar:settings:autopersonal:title' => "Events automatisch in den persönlichen Kalender des Benutzers eintragen, der das Event hinzufügt.",
	'event_calendar:settings:autogroup:title' => "Gruppen-Events automatisch in die persönlichen Kalender aller Gruppenmitglieder eintragen.",
	'event_calendar:settings:agenda_view:title' => "Agenda-Ansicht verwenden",
	'event_calendar:settings:venue_view:title' => "Ort des Events in der Übersichts-Ansicht (Auflistung der Events) anzeigen",
	'event_calendar:settings:yes' => "Ja",
	'event_calendar:settings:no' => "Nein",
	'event_calendar:settings:site_calendar:title' => "Kalender der Community-Seite anzeigen",
	'event_calendar:settings:site_calendar:admin' => "Ja, nur Admins können Events hinzufügen",
	'event_calendar:settings:site_calendar:loggedin' => "Ja, alle angemeldeten Benutzer können Events hinzufügen",
	'event_calendar:settings:group_calendar:title' => "Gruppen-Kalender",
	'event_calendar:settings:group_calendar:admin' => "Ja, nur Admins und der Gründer der Gruppe können Events hinzufügen",
	'event_calendar:settings:group_calendar:members' => "Ja, alle Gruppenmitglieder können Events hinzufügen",
	'event_calendar:settings:group_default:title' => "Bei neuen Gruppen soll standardmäßig ein Gruppen-Kalender erzeugt werden (wenn die Option Gruppen-Kalender aktiviert ist)",
	'event_calendar:settings:group_default:no' => "Nein (aber Admins oder der Gründer der Gruppe kann den Gruppen-Kalender aktivieren)",
	'event_calendar:settings:group_default:yes' => "Ja (aber Admins oder der Gründer der Gruppe kann den Gruppen-Kalender deaktivieren)",
	'event_calendar:settings:group_always_display:title' => "Wenn die Option Gruppen-Kalender aktiviert ist, den Gruppenkalender immer auf der Profilseite der Gruppe anzeigen (auch wenn der Kalender leer ist)",
	'event_calendar:settings:region_display:title' => "Das Feld Region zu Events hinzufügen",
	'event_calendar:settings:region_list:title' => "Liste von Regionen (eine pro Zeile)",
	'event_calendar:region_label' => "Region",
	'event_calendar:region_description' => "Optional. Wähle die Region, in der dieses Event stattfindet.",
	'event_calendar:settings:type_display:title' => "Das Feld Art des Events zu Events hinzufügen",
	'event_calendar:settings:type_list:title' => "Liste von Arten von Events (eine pro Zeile)",
	'event_calendar:type_label' => "Art des Events",
	'event_calendar:type_description' => "Optional. Wähle die Art des Events.",
	'event_calendar:all' => "Alle",
	'event_calendar:region_filter_by_label' => "Filtere nach Region:",
	'event_calendar:settings:first_date:title' => "Frühstmögliches zulässiges Datum (im YYYY-MM-DD Format)",
	'event_calendar:settings:last_date:title' => "Letztmögliches zulässiges Datum (im YYYY-MM-DD Format)",
	'event_calendar:enable_event_calendar' => "Gruppen-Kalender aktivieren",
	'event_calendar:no_events_found' => "Es wurden keine Events gefunden.",
	'event_calendar:mine' => "Meine",
	'event_calendar:feature' => "Zu \"Besondere Events\" hinzufügen",
	'event_calendar:unfeature' => "Aus \"Besondere Events\" entfernen",
	'event_calendar:agenda:column:time' => "Zeit",
	'event_calendar:agenda:column:session' => "Session",
	'event_calendar:agenda:column:venue' => "Ort",
	'event_calendar:upcoming_events_title' => "Bevorstehende Events",
	'event_calendar:settings:paged' => "Auflistung mit Seitenumbruch",
	'event_calendar:settings:month' => "Nach Monat sortiert",
	'event_calendar:settings:listing_format:title' => "Format der Event-Ansicht",
	'event_calendar:paged:column:date' => "Datum",
	'event_calendar:paged:column:time'	=> "Zeit",
	'event_calendar:paged:column:event' => "Event",
	'event_calendar:paged:column:venue' => "Ort",
	'event_calendar:paged:column:calendar' => "Kalender",

	/**
	 * Event calendar river
	 **/

	//generic terms to use
    'event_calendar:river:created' => "%s erstellte",
    'event_calendar:river:updated' => "%s aktualisierte",
    'event_calendar:river:annotated1' => "%s hat",
	'event_calendar:river:annotated2' => "in ihren / seinen persönlichen Kalender aufgenommen.",

	//these get inserted into the river links to take the user to the entity
    'event_calendar:river:create' => "ein neues Event mit dem Titel",
    'event_calendar:river:the_event' => "ein Event mit dem Titel",

	);

	add_translation("de",$german);

?>