<?php
/**
 * iZAP izap_videos
 *
 * @package Elgg videotizer, by iZAP Web Solutions.
 * @license GNU Public License version 3
 * @Contact iZAP Team "<support@izap.in>"
 * @Founder Tarun Jangra "<tarun@izap.in>"
 * @link http://www.izap.in/
 * @version 3.7b
 */
$german = array (
        'izap_videos' => "iZAP Videos",
        'item:object:izap_recycle_bin' => 'Videos im Papierkorb',
        'videos' => "Videos",
        'item:object:izapVideoQueue' => 'Videos in Warteschlange',
        'izap_videos:videos' => "Meine Videos",
        'izap_videos:add' => "Video hinzufügen",
        'izap_videos:uploadVideo' => "Video hochladen",
        'izap_videos:addgroupVideo' => "Gruppen-Video hinzufügen",
        'izap_videos:user' => "Videos von %s",
        'izap_videos:title' => "Gebe den Titel ein",
        'izap_videos:getvideo' => "Video abrufen",
        'izap_videos:access' => "Zugriff",
        'izap_videos:tags' => "Video-Tags",
        'izap_videos:blank' => "Bitte gebe eine gültige URL ein",
        'izap_videos:blanktitle' => "Bitte gebe den Titel ein",
        'izap_videos:saveerror' => "Entschuldigung. Das Video konnte nicht gespeichert werden",
        'izap_videos:saved' => "Dein Video wurde gespeichert.",
        'izap_videos:everyone' => "Alle Videos",
        'izap_videos:time' => "Hinzugefügt: %s",
        'izap_videos:remove' => "Möchtest Du dieses Video löschen?",
        'izap_videos:deleted' => "Das Video wurde gelöscht",
        'izap_videos:notdeleted' => "Das Video konnte nicht gelöscht werden",
        'izap_videos:wrongid' => "Entschuldigung. Entweder wurde das Video bereits gelöscht oder die ID des Videos ist nicht richtig",
        'izap_videos:frnd' => "Videos meiner Freunde",
        'izap_videos:userfrnd' => "Videos der Freunde von %s",
        'izap_videos:all' => "Alle Videos der Community-Seite",
        'izap_videos:river:added' => "%s ",
        'izap_videos:river:video' => "hat ein neues Video hinzugefügt",
        'izap_videos:river:annotate' => " schrieb einen Kommentar zu ",
        'izap_videos:widget' => "Die zuletzt hinzugefügten Videos anzeigen",
        'item:object:izap_videos' => "Videos",
        'izap_videos:numbertodisplay' => "Anzahl der anzuzeigenden Videos.",
        'izap_videos:play' => "Das ausgewählte Video abspielen",
        'izap_videos:play:widget' => "Dieses Widget spielt das von Dir gewählte Video ab",
        'izap_videos:chosevideo' => "Wähle ein Video aus, das abgespielt werden soll",
        'izap_videos:notfound' => "Es wurde noch kein Video hinzugefügt.",
        'izap_videos:error' => "Bei der Datenabfrage vom Remoteserver ist ein Fehler aufgetreten. Entweder ist die URL falsch oder das Video ist nicht verfügbar.",
        'izap_videos:addtoyour' => "Kopiere dieses Video zu meinen Videos.",
        'izap_videos:condition' => "* Diese Eingaben für Titel, Tags und Beschreibung überschreiben die ursprünglichen Informationen.<br>* Eine Bezugsquelle ist das Hinzufügen eines Video ist notwendig (entweder eine URL oder ein Video zum Hochladen)",
        'izap_videos:geterror' => "Das Einbinden des Video ist fehlgeschlagen. Der Remoteserver antwortet nicht.",
        'izap_videos:description' => "Beschreibung",
        'izap_videos:edit' => "Bearbeiten",
        'izap_videos:editVideo' => "Video bearbeiten",
        'izap_videos:copyVideo' => "Video kopieren",
        'izap_videos:blank:title' => "Die Angabe eines Titel ist notwendig",
        'izap_videos:save' => "Speichern",
        'izap_videos:missingfields' => "Es fehlen eine oder mehrere notwendige Eingaben.",
        'izap_videos:autoplay' => "Autoplay aktivieren",
        'izap_videos:views' => "Zugriffe",
        'izap_videos:tagcloud' => "Meistverwendete Video-Tags",
        'izap_videos:top' => "Beliebteste Videos",
        'izap_videos:fopenerror' => "Bitte den Server-Administrator, <b>'allow_url_fopen = On'</b> in der Konfigurationsdatei php.ini zu setzen.",
        'izap_videos:errorCode' => "Das Einbinden des Video ist fehlgeschlagen. Entweder ist die URL fehlerhaft, das Video ist nicht verfügbar oder das Einbinden des Videos auf anderen Seiten ist nicht möglich.",
        'izap_videos:errorCode101' => "",
        'izap_videos:errorCode102' => "",
        'izap_videos:errorCodeArray' => "Das Einbinden des Video ist fehlgeschlagen. Entweder ist die URL fehlerhaft, das Video ist nicht verfügbar oder das Einbinden des Videos auf anderen Seiten ist nicht möglich.",
        'izap_videos:latest' => "Die neuesten Videos",
        'izap_videos:groups' => "Videos von %s",
        'izap_videos:group:enablevideo' => "Gruppen-Videos aktivieren",
        'izap_videos:groupvideos' => "Gruppen-Videos",
        'izap_videos:izapUploadOption' => "%s",
        'izap_videos:upload' => "Ein Video hochladen (unterstützt werden 3gp, avi, mp4, flv, wmv)",
        'izap_videos:converterror' => "Beim Konvertieren des Videos ist ein Fehler aufgetreten.",
        'izap_videos:izapBorderColor1' => "Hintergrundfarbe für den Videoplayer: (Eingabeformat: 0x13ABEC)",
        'izap_videos:izapBorderColor2' => "Vordergrundfarbe für den Videoplayer: (Eingabeformat: 0x13ABEC)",
        'izap_videos:izapBarColor' => "Farbe für die Symbolleiste des Videoplayers: (Eingabe des Farbcodes ohne '#')",
        'izap_videos:river:titled' => '%s hat ein neues Video mit dem Titel %s hinzugefügt',
        'izap_videos:latestvideos' => "Neueste",
        'izap_videos:topViewed' => "Meist angesehene",
        'izap_videos:topCommented' => "Meist kommentierte",
        'izap_videos:embedCode' => "Sharing- und Embed-Code",
        'izap_videos:videoGal' => "iZAP Video-Gallerie",
        'izap_videos:noTagVideo' => "Keine Videos für dieses Tag gefunden.",
        'izap_videos:choosemethod' => 'Wähle die Methode',
        'izap_videos:noVideo' => 'Entschuldigung. Es wurde kein Videogefunden',
        'izap_videos:izapPhpInterpreter' => 'Pfad zum PHP-Interpreter, z.B. /usr/bin/php',
        'izap_videos:izapFfmpegConvert' => 'FFMPEG-Konvertierungs-Befehl. (Verändere "[inputs]" nicht!)',
        'izap_videos:izapFfmpegWatermark' => 'Pfad zur Video-Watermarking-Library.',
        'izap_videos:izapFfmpegImage' => 'FFMPEG-Snapshot-Befehl. (Verändere "[inputs]" nicht!)',
        'izap_videos:processed' => 'Das Video wurde in die Warteschlange zur Konvertierung hinzugefügt.',
        'izap_videos:izapIndexPageWidget' => 'Videos-Widget auf der Index-Seite anzeigen',
        'izap_videos:izapTopBarWidget' => 'Hochladen-Schaltfläche zur Elgg-Topbar hinzufügen',
        'izap_videos:copiedFrom' => 'Kopiert von',
        'izap_videos:noDescription' => 'Der Besitzer des Videos hat noch keine Beschreibung hinzugefügt.',
        'izap_videos:queueManagement' => 'Warteschlangen-Verwaltung',
        'izap_videos:queueStatus' => 'Warteschlangen-Status',
        'izap_videos:notRunning' => 'Läuft nicht',
        'izap_videos:running' => 'Läuft',
        'izap_videos:error_videos' => 'Fehlerhafte Video-Konvertierungen',
        'izap_videos:queuedFilesTotal' => 'Videodateien in Warteschlange',
        'izap_videos:resetNow' => 'Jetzt zurücksetzen',
        'izap_videos:deleteNow' => 'Jetzt löschen',
        'izap_video:deleteQueue' => 'Bist Du sicher, dass Du die Warteschlange löschen willst? Dadurch werden alle Videos in der Warteschlange, die noch nicht konvertiert sind gelöscht. Das Löschen kann nicht rückgängig gemacht werden.',
        'izap_videos:maxFileSize' => 'Maximal erlaubte Dateigröße (%s Mb)',
        'izap_videos:enterMaxFileSize' => '',
        'izap_videos:fileNotFound' => 'Datei nicht gefunden.',
        'izap_videos:noOptionSelected' => 'Das Hinzufügen von Videos wurde durch den Administrator deaktiviert.',
        'izap_videos:izapFfmpegObject' => 'Pfad zum Bild oder Eingabe des Textes für das Wasserzeichen.',
        'izap_videos:izapFfmpegObjectMarque' => 'Soll ein Text-Wasserzeichen verwendet werden?',
        'izap_videos:izapFfmpegObjectPosition' => 'Wo soll das Wasserzeichen eingeblendet werden?',
        'izap_videos:comments' => 'Kommentare',
        'izap_videos:restore' => 'Wiederherstellen',
        'izap_videos:send_user_message' => 'Sende eine Nachricht an den Benutzer',
        'izap_videos:error_reason' => 'Fehlerursache : %s',


        'izap_videos:form:upload' => 'Hochladen',
        'izap_videos:form:enterUrl' => 'URL angeben',
        'izap_videos:form:embedCode' => 'Embed-Code',
        'izap_videos:form:izapVideoUrl' => 'Gebe die URL des Videos ein * <a href="#supportedSites">Unterstützte Seiten</a>',
        'izap_videos:form:izapSupportedSites' => 'Unterstützte Seiten.',
        'izap_videos:form:izapVideoFile' => 'Ein Video hochladen * <a href="#supportedFormats">Unterstützte Video-Formate</a>',
        'izap_videos:form:izapSupportedFormats' => 'Unterstützte Video-Formate.',
        'izap_videos:form:izapVideoEmbed' => 'Gebe den vollständigen Embed-Code ein *',
        'izap_videos:form:izapVideoTitle' => 'Gebe den Titel des Videos ein *',
        'izap_videos:form:izapVideoDescription' => 'Gebe eine Beschreibung für das Video ein',
        'izap_videos:form:izapVideoTags' => 'Gebe die Tags für das Video ein',
        'izap_videos:form:izapVideoAccess' => 'Zugriffslevel für das Video',
        'izap_videos:form:izapVideoOptionalImage' => 'Vorschaubild hochladen',
        'izap_videos:form:izapAccessMsg' => '<em class="izap_normal_text izap_notice">Du kannst den Zugriffslevel vor Abschluß der Videokonvertierung nicht ändern.</em>',
        'izap_videos:form:izapEditMsg' => '<em class="izap_normal_text izap_notice">Eine Bearbeitung ist vor Abschluß der Videokonvertierung nicht möglich.</em>',
        'izap_videos:form:izapTrashedVideoMsg' => '<em class="izap_normal_text izap_notice">Das Videoformat wird nicht unterstützt.</em>',



        // error messages
        'izap_videos:error:uploadNotSupported' => 'Das Hochladen von Dateien ist noch nicht möglich.',
        'izap_videos:error:notUploaded' => 'Beim Hochladen der Datei ist ein Fehler aufgetreten',
        'izap_videos:error:invalidInput' => 'Ungültige oder fehlende Eingabe.',
        'izap_videos:error:zeroFile' => 'Keine Datei ausgewählt oder ausgewählte Datei ist leer.',
        'izap_videos:error:maxFile' => 'Die ausgewählte Datei ist größer als die maximal erlaubte Dateigröße.',
        'izap_videos:error:embedCode' => '',
        'izap_videos:error:videoOptionBlank' => 'Es wurde keine Option zum Hinzufügen eines Videos gewählt.',
        'izap_videos:error:adminSettingsReset' => 'Die Einstellungen konnten nicht zurückgesetzt werden.',
        'izap_videos:error:unknownFileType' => 'Das Dateiformat wurde nicht erkannt.',
        'izap_videos:error:notValidUrl' => 'Ungültige URL',
        'izap_videos:error:unsupportedUrl' => 'Diese URL wird nicht unterstützt',
        'izap_videos:error:code:101' => 'Das Einbinden des Video ist fehlgeschlagen. Der Remoteserver antwortet nicht.',
        'izap_videos:error:code:102' => 'Dieses Video stammt nicht von Veoh. Bitte gebe eine URL von Veoh an.',
        'izap_videos:error:code:103' => 'Diese URL wird nicht unterstützt',
        'izap_videos:error:code:104' => 'Beim Hochladen der Datei ist ein Fehler aufgetreten',
        'izap_videos:error:code:105' => 'Keine Datei ausgewählt oder ausgewählte Datei ist leer.',
        'izap_videos:error:code:106' => 'Das Dateiformat wird nicht unterstützt.',
        'izap_videos:error:code:107' => 'Die ausgewählte Datei ist größer als die maximal erlaubte Dateigröße.',
        'izap_videos:error:code:108' => 'Die ID des Video ist ungültig.',
        'izap_videos:error:code:109' => '',
        'izap_videos:error:code:110' => '',
        'izap_videos:error:code:111' => '',
        'izap_videos:error:code:112' => '',
        'izap_videos:error:code:113' => '',
        'izap_videos:error:code:114' => '',
        'izap_videos:error:code:Array' => 'Unbekannter Fehler bei der Einbindung des Videos. Mögliche Ursache sind nicht ausreichende Zugriffsrechte.',
        'izap_videos:error:emptyTitle' => 'Der Titel des Videos muss angegeben werden.',
        'izap_videos:error:save' => 'Beim Speichern des Videos ist ein Fehler aufgetreten.',
        'izap_videos:error:unsupported' => 'Das Videoformat wird nicht unterstützt.',
        'izap_videos:error:emptyEmbedCode' => 'Bitte gebe den Embed-Code an.',
        'izap_videos:error:sqliteDrivers' => 'Bitte installiere die PDO-Sqlite-Treiber, um Onserver-Videos zu ermöglichen.',

        // success message
        'izap_videos:success:videoCopied' => 'Das Video wurde kopiert',
        'izap_videos:success:videoNotCopied' => 'Das Kopieren des Videos ist fehlgeschlagen',
        'izap_videos:success:adminSettingsSaved' => 'Die Einstellungen wurden gespeichert.',
        'izap_videos:success:adminSettingsReset' => 'Die Einstellungen wurden zurückgesetzt.',
        'izap_videos:success:save' => 'Das Video wurde gespeichert',

        //notify messages
        'izap_videos:newVideoAdded' => 'Ein neues Video wurde hinzugefügt',
        'izap_videos:notifySub:videoConverted' => 'Video wurde konvertiert.',
        'izap_videos:notifyMsg:videoConverted' => 'Dein Video wurde konvertiert. Folge dem Link, um Dein Video anzusehen: %s',
        'izap_videos:notifySub:videoNotConverted' => 'Die Konvertierung des Videos ist fehlgeschlagen.',
        'izap_videos:notifyAdminMsg:videoNotConverted' => 'Beim Hinzufügen eines Videos durch einen Benutzer ist ein Fehler aufgetreten.<br />Fehlermeldung: <b>%s</b>',
        'izap_videos:notifyUserMsg:videoNotConverted' => 'Bei der Verarbeitung Deines Videos ist ein Fehler aufgetreten. Der Admin wurde bereits darüber informiert.',
        'izap_videos:notifySub:unConverted_video' => 'Es gibt ein Video, das nicht konvertiert werden konnte',
        'izap_videos:notifyMsg:unConverted_video' => 'Beim Hinzufügen eines Videos durch einen Benutzer ist ein Fehler aufgetreten. Das nicht-konvertierte Video befindet sich hier: <br /><b>%s</b>',
        'izap_videos:notifySub:video_deleted' => 'Dein Video wurde gelöscht',



        // admin settings
        'izap_videos:adminSettings:tabs_settings' => 'Einstellungen',
        'izap_videos:adminSettings:tabs_queue_status' => 'Warteschlangen-Status',
        'izap_videos:adminSettings:tabs_server_analysis' => 'Server-Überprüfung',
        'izap_videos:adminSettings:tabs_recycle_bin' => 'Papierkorb',

        'izap_videos:adminSettings' => 'Video-Einstellungen',
        'izap_videos:adminSettings:settings' => 'Einstellungen für iZAP-Videos',
        'izap_videos:adminSettings:gotoSettings' => 'Gehe zu den Admin-Einstellungen',
        'izap_videos:adminSettings:onServerVideos' => extension_loaded('pdo_sqlite')?'Onserver-Videos':'Onserver-Videos (<em class="izap_notice izap_small_text">Aktiviere/Installiere die PDO-Sqlite-Treiber, um das Onserver-Video-Feature verwenden zu können.</em>)',
        'izap_videos:adminSettings:offServerVideos' => 'Offserver-Videos',
        'izap_videos:adminSettings:embedCode' => 'Embed-Code',
        'izap_videos:adminSettings:izapVideoOptions' => 'Optionen für Videos',
        'izap_videos:adminSettings:izapPhpInterpreter' => 'Pfad zum PHP-Interpreter',
        'izap_videos:adminSettings:izapVideoCommand' => 'Befehl für die Video-Konvertierung',
        'izap_videos:adminSettings:izapVideoThumb' => 'Befehl zum Erzeugen des Vorschaubildes',
        'izap_videos:adminSettings:izapBarColor' => 'Farbe für den Videoplayer',
        'izap_videos:adminSettings:izapBorderColor1' => 'Farbe für den Fortschrittsbalken des Videoplayers',
        'izap_videos:adminSettings:izapBorderColor2' => 'Textfarbe im Videoplayer',
        'izap_videos:adminSettings:izapBorderColor3' => 'Farbe der Schaltflächen im Videoplayer',
        'izap_videos:adminSettings:izapMaxFileSize' => 'Maximal erlaubte Dateigröße für Video-Uploads (in Mb.)',
        'izap_videos:adminSettings:izapExtendVideoSupport' => 'Erweiterte Video-URL-Unterstützung von iZAP aktivieren',
        'izap_videos:adminSettings:extendVideoSupport' => 'Ja',
        'izap_videos:adminSettings:izapIndexPageWidget' => 'Videos-Widget auf der Index-Seite anzeigen',
        'izap_videos:adminSettings:addOnHomePage' => 'Ja',
        'izap_videos:adminSettings:izapTopBarWidget' => 'Hochladen-Link in der Topbar anzeigen',
        'izap_videos:adminSettings:addOnTopBar' => 'Ja',
        'izap_videos:adminSettings:izapKeepOriginal' => 'Original-Datei nach Konvertierung auf dem Server belassen',
        'izap_videos:adminSettings:keep-original' => 'Ja',
        'izap_videos:adminSettings:izapGiveUsCredit' => 'Willst Du einen Link zur iZAP-Seite einblenden?',
        'izap_videos:adminSettings:giveUsCredit' => 'Ja',
        'izap_videos:adminSettings:notForWindows' => 'Deaktivierte Felder sind auf Windows-Servern nicht verfügbar',
        'izap_videos:adminSettings:resetSettings' => 'Standardeinstellungen wiederherstellen',
        'izap_videos:adminSettings:izap_cron_time' => 'Konfiguriere die Cron-Einstellung zur automatischen Reinitialisierung der Warteschlange',
        'izap_videos:adminSettings:minute' => 'Eine Minute',
        'izap_videos:adminSettings:fiveminute' => '5 Minuten',
        'izap_videos:adminSettings:fifteenmin' => '15 Minuten',
        'izap_videos:adminSettings:halfhour' => '30 Minuten',
        'izap_videos:adminSettings:hourly' => 'Eine Stunde',
        'izap_videos:adminSettings:save' => 'Einstellungen speichern',
        'izap_videos:adminSettings:cron_not_installed' => '<em class="izap_normal_text izap_notice">Aktiviere das Crontrigger-Plugin bzw. konfiguriere die Crontab auf Deinem Server wie unter <a href="http://docs.elgg.org/wiki/Cron">http://docs.elgg.org/wiki/Cron</a> beschrieben, um die Warteschlange regelmäßig automatisch reinitialisieren zu können, falls bei einer Konvertierung eine Unterbrechung aufgetreten ist.</em>',
        'izap_videos:adminSettings:cron_off' => 'Deaktivieren',
        'izap_videos:adminSettings:messages_plugin_missing' => '<em class="izap_notice">Aktiviere das Messages-Plugin, damit die Benutzer darüber informiert werden können, warum ein Video gelöscht wurde.</em>',
        'izap_videos:adminSettings:deleted_from_trash' => 'Das Video wurde aus dem Papierkorb gelöscht.',
        'izap_videos:adminSettings:reset_queue' => 'Die Warteschlange ist nun leer.',
        'izap_videos:adminSettings:restore_video' => 'Die Wiederherstellung war erfolgreich.',
        // info messages
        'izap_videos:adminSettings:info:convert-command' => 'Optimierte Parameter für den Befehl zur Videokonvertierung: /path/of/ffmpeg -y -i [inputVideoPath] -vcodec libx264 -vpre hq  -b 300k  -bt 300k  -acodec libfaac  -ar 22050  -ab 48k [outputVideoPath]',
        'izap_videos:adminSettings:info:give-credit' => 'Hinzufügen eines Links zur iZAP-Seite im Footer der Community-Seite. Du kannst auch eine Dankesnachricht an <a href="mailto:reviews@izap.in">reviews@izap.in</a> senden',
        'izap_videos:adminSettings:info:bg-color' => 'Gebe den Farbcode im HEX-Format ohne # an. Z.B. #FFFFFF ist der Code für weiß. In diesem Fall müßtes Du "FFFFFF" eingeben ',
        'izap_videos:adminSettings:info:izapKeepOriginal' => 'Abwählen, falls die Originaldatei nach der Konvertierung gelöscht werden soll',

        // add/edit form
        'izap_videos:addEditForm:ONSERVER' => 'Video hochladen',
        'izap_videos:addEditForm:OFFSERVER' => 'Video-URL hinzufügen',
        'izap_videos:addEditForm:EMBED' => 'Video-Embed-Code hinzufügen',
        'izap_videos:addEditForm:title' => 'Titel',
        'izap_videos:addEditForm:videoImage' => 'Vorschaubild (optional)',
        'izap_videos:addEditForm:description' => 'Beschreibung',
        'izap_videos:addEditForm:access_id' => 'Zugangslevel',
        'izap_videos:addEditForm:tags' => 'Tags',
        'izap_videos:addEditForm:guid' => '',
        'izap_videos:addEditForm:container_guid' => '',
        'izap_videos:addEditForm:videoUrl' => 'Video-URL',
        'izap_videos:addEditForm:videoType' => '',
        'izap_videos:addEditForm:videoFile' => 'Video-Datei',
        'izap_videos:addEditForm:videoEmbed' => 'Video-Embed-Code',
        'izap_videos:addEditForm:' => '',
        'izap_videos:addEditForm:' => '',
        'izap_videos:addEditForm:' => '',
        'izap_videos:addEditForm:' => '',
        'izap_videos:addEditForm:' => '',
        'izap_videos:addEditForm:save' => 'Speichern',

        'izap_videos:please_wait' => 'Bitte warten, bis das Speichern abgeschlossen ist...',
        'izap_videos:my_favorites' => 'Meine Favoriten',
        'izap_videos:user_favorites' => 'Favoriten von %s',
        'izap_videos:save_favorite' => 'Zu Favoriten hinzufügen',
        'izap_videos:favorite_saved' => 'Das Video wurde zur Liste Deiner Favoriten hinzugefügt.',
        'izap_videos:favorite_removed' => 'Das Video wurde aus der Liste Deiner Favoriten entfernt.',
        'izap_videos:remove_favorite' => 'Aus den Favoriten entfernen',
        'izap_videos:no_favorites' => 'Du hast noch keine Videos zur Liste Deiner Favoriten hinzugefügt.',
);add_translation("de",$german);
